AllCops:
  Include:
    - "Rakefile"
    - "**/*.rb"
  Exclude:
    - "vendor/**/*"
    - "activejob-retry.gemspec"
    - "Gemfile"

LineLength:
  Max: 90

Style/SignalException:
  EnforcedStyle: 'only_raise'

Style/Documentation:
  Enabled: false

Style/DotPosition:
  EnforcedStyle: trailing

Style/GuardClause:
  Enabled: false

Metrics/MethodLength:
  CountComments: false

Metrics/BlockLength:
  CountComments: false
  Exclude:
    - spec/**/*
